// Mocks generated by Mockito 5.4.6 from annotations
// in mmine/test/features/music_player/presentation/bloc/playback/playback_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mmine/core/error/failures.dart' as _i6;
import 'package:mmine/core/usecases/usecase.dart' as _i10;
import 'package:mmine/features/music_player/domain/entities/audio_track.dart'
    as _i7;
import 'package:mmine/features/music_player/domain/entities/playback_state.dart'
    as _i5;
import 'package:mmine/features/music_player/domain/repositories/playback_repository.dart'
    as _i3;
import 'package:mmine/features/music_player/domain/usecases/playback/pause_playback_use_case.dart'
    as _i9;
import 'package:mmine/features/music_player/domain/usecases/playback/play_track_use_case.dart'
    as _i8;
import 'package:mmine/features/music_player/domain/usecases/playback/resume_playback_use_case.dart'
    as _i11;
import 'package:mmine/features/music_player/domain/usecases/playback/seek_to_position_use_case.dart'
    as _i12;
import 'package:mmine/features/music_player/domain/usecases/playback/set_speed_use_case.dart'
    as _i14;
import 'package:mmine/features/music_player/domain/usecases/playback/set_volume_use_case.dart'
    as _i13;
import 'package:mmine/features/music_player/domain/usecases/playback/toggle_shuffle_use_case.dart'
    as _i18;
import 'package:mmine/features/music_player/domain/usecases/queue/set_queue_use_case.dart'
    as _i15;
import 'package:mmine/features/music_player/domain/usecases/queue/skip_to_next_use_case.dart'
    as _i16;
import 'package:mmine/features/music_player/domain/usecases/queue/skip_to_previous_use_case.dart'
    as _i17;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaybackRepository_1 extends _i1.SmartFake
    implements _i3.PlaybackRepository {
  _FakePlaybackRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlaybackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaybackRepository extends _i1.Mock
    implements _i3.PlaybackRepository {
  MockPlaybackRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.PlaybackState> get playbackStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#playbackStateStream),
            returnValue: _i4.Stream<_i5.PlaybackState>.empty(),
          )
          as _i4.Stream<_i5.PlaybackState>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> play(_i7.AudioTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#play, [track]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#play, [track]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#pause, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#resume, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#stop, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> seekTo(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seekTo, [position]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#seekTo, [position]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> skipToNext() =>
      (super.noSuchMethod(
            Invocation.method(#skipToNext, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#skipToNext, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> skipToPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#skipToPrevious, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#skipToPrevious, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setVolume, [volume]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeed, [speed]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setSpeed, [speed]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setRepeatMode(
    _i5.RepeatMode? mode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setRepeatMode, [mode]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setRepeatMode, [mode]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setShuffleEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setShuffleEnabled, [enabled]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setShuffleEnabled, [enabled]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setQueue(
    List<_i7.AudioTrack>? tracks,
    int? startIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setQueue, [tracks, startIndex]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setQueue, [tracks, startIndex]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> addToQueue(
    List<_i7.AudioTrack>? tracks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToQueue, [tracks]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#addToQueue, [tracks]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> playNext(
    List<_i7.AudioTrack>? tracks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#playNext, [tracks]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#playNext, [tracks]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> removeFromQueue(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromQueue, [index]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#removeFromQueue, [index]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> reorderQueue(
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderQueue, [oldIndex, newIndex]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#reorderQueue, [oldIndex, newIndex]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> clearQueue() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueue, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#clearQueue, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [PlayTrackUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayTrackUseCase extends _i1.Mock implements _i8.PlayTrackUseCase {
  MockPlayTrackUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(_i7.AudioTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#call, [track]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [track]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [PausePlaybackUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPausePlaybackUseCase extends _i1.Mock
    implements _i9.PausePlaybackUseCase {
  MockPausePlaybackUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(_i10.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [ResumePlaybackUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResumePlaybackUseCase extends _i1.Mock
    implements _i11.ResumePlaybackUseCase {
  MockResumePlaybackUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(_i10.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [SeekToPositionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeekToPositionUseCase extends _i1.Mock
    implements _i12.SeekToPositionUseCase {
  MockSeekToPositionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#call, [position]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [position]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [SetVolumeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetVolumeUseCase extends _i1.Mock implements _i13.SetVolumeUseCase {
  MockSetVolumeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#call, [volume]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [volume]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [SetSpeedUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetSpeedUseCase extends _i1.Mock implements _i14.SetSpeedUseCase {
  MockSetSpeedUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#call, [speed]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [speed]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [SetQueueUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetQueueUseCase extends _i1.Mock implements _i15.SetQueueUseCase {
  MockSetQueueUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(_i15.SetQueueParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [SkipToNextUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSkipToNextUseCase extends _i1.Mock implements _i16.SkipToNextUseCase {
  MockSkipToNextUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(_i10.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [SkipToPreviousUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSkipToPreviousUseCase extends _i1.Mock
    implements _i17.SkipToPreviousUseCase {
  MockSkipToPreviousUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(_i10.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [ToggleShuffleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleShuffleUseCase extends _i1.Mock
    implements _i18.ToggleShuffleUseCase {
  MockToggleShuffleUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlaybackRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePlaybackRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.PlaybackRepository);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> call(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#call, [enabled]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [enabled]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}
