include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - submodules/
    - integration_test/
    - build/**

linter:
  rules:
    use_key_in_widget_constructors: false
    prefer_single_quotes: true
    sort_pub_dependencies: true
    always_use_package_imports: true
    directives_ordering: true
    unawaited_futures: true
    discarded_futures: true
