// Mocks generated by Mockito 5.4.6 from annotations
// in mmine/test/features/music_player/domain/usecases/queue/skip_to_next_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mmine/core/error/failures.dart' as _i6;
import 'package:mmine/features/music_player/domain/entities/audio_track.dart'
    as _i7;
import 'package:mmine/features/music_player/domain/entities/playback_state.dart'
    as _i5;
import 'package:mmine/features/music_player/domain/repositories/playback_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlaybackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaybackRepository extends _i1.Mock
    implements _i3.PlaybackRepository {
  MockPlaybackRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.PlaybackState> get playbackStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#playbackStateStream),
            returnValue: _i4.Stream<_i5.PlaybackState>.empty(),
          )
          as _i4.Stream<_i5.PlaybackState>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> play(_i7.AudioTrack? track) =>
      (super.noSuchMethod(
            Invocation.method(#play, [track]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#play, [track]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#pause, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#resume, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#stop, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> seekTo(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seekTo, [position]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#seekTo, [position]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> skipToNext() =>
      (super.noSuchMethod(
            Invocation.method(#skipToNext, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#skipToNext, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> skipToPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#skipToPrevious, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#skipToPrevious, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setVolume, [volume]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeed, [speed]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setSpeed, [speed]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setRepeatMode(
    _i5.RepeatMode? mode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setRepeatMode, [mode]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setRepeatMode, [mode]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setShuffleEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setShuffleEnabled, [enabled]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setShuffleEnabled, [enabled]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> setQueue(
    List<_i7.AudioTrack>? tracks,
    int? startIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setQueue, [tracks, startIndex]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#setQueue, [tracks, startIndex]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> addToQueue(
    List<_i7.AudioTrack>? tracks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToQueue, [tracks]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#addToQueue, [tracks]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> playNext(
    List<_i7.AudioTrack>? tracks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#playNext, [tracks]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#playNext, [tracks]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> removeFromQueue(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromQueue, [index]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#removeFromQueue, [index]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> reorderQueue(
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderQueue, [oldIndex, newIndex]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#reorderQueue, [oldIndex, newIndex]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> clearQueue() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueue, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#clearQueue, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);
}
