// Mocks generated by Mockito 5.4.6 from annotations
// in mmine/test/features/music_player/domain/usecases/audio/search_tracks_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mmine/core/error/failures.dart' as _i5;
import 'package:mmine/features/music_player/domain/entities/audio_track.dart'
    as _i6;
import 'package:mmine/features/music_player/domain/repositories/audio_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AudioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRepository extends _i1.Mock implements _i3.AudioRepository {
  MockAudioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>> scanDirectory(
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scanDirectory, [path]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AudioTrack>>(
                    this,
                    Invocation.method(#scanDirectory, [path]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>> getAllTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTracks, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AudioTrack>>(
                    this,
                    Invocation.method(#getAllTracks, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>> getTracksByArtist(
    String? artist,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTracksByArtist, [artist]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AudioTrack>>(
                    this,
                    Invocation.method(#getTracksByArtist, [artist]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>> getTracksByAlbum(
    String? album,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTracksByAlbum, [album]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AudioTrack>>(
                    this,
                    Invocation.method(#getTracksByAlbum, [album]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AudioTrack>> getTrackById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackById, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AudioTrack>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AudioTrack>(
                    this,
                    Invocation.method(#getTrackById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AudioTrack>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getAllArtists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllArtists, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                  _FakeEither_0<_i5.Failure, List<String>>(
                    this,
                    Invocation.method(#getAllArtists, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getAllAlbums() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAlbums, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                  _FakeEither_0<_i5.Failure, List<String>>(
                    this,
                    Invocation.method(#getAllAlbums, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>> searchTracks(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTracks, [query]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.AudioTrack>>(
                    this,
                    Invocation.method(#searchTracks, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AudioTrack>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteTrack(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrack, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteTrack, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> clearLibrary() =>
      (super.noSuchMethod(
            Invocation.method(#clearLibrary, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#clearLibrary, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
