// Mocks generated by Mockito 5.4.6 from annotations
// in mmine/test/features/music_player/data/repositories/audio_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;
import 'dart:typed_data' as _i6;

import 'package:mmine/features/music_player/data/datasources/database.dart'
    as _i10;
import 'package:mmine/features/music_player/data/datasources/file_system_data_source.dart'
    as _i2;
import 'package:mmine/features/music_player/data/datasources/local_database_data_source.dart'
    as _i8;
import 'package:mmine/features/music_player/data/datasources/metadata_data_source.dart'
    as _i5;
import 'package:mmine/features/music_player/data/datasources/permission_data_source.dart'
    as _i11;
import 'package:mmine/features/music_player/data/models/audio_track_model.dart'
    as _i9;
import 'package:mmine/features/music_player/domain/entities/audio_track.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FileSystemDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileSystemDataSource extends _i1.Mock
    implements _i2.FileSystemDataSource {
  MockFileSystemDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.File>> scanDirectory(String? directoryPath) =>
      (super.noSuchMethod(
            Invocation.method(#scanDirectory, [directoryPath]),
            returnValue: _i3.Future<List<_i4.File>>.value(<_i4.File>[]),
          )
          as _i3.Future<List<_i4.File>>);

  @override
  _i3.Future<bool> validateAudioFormat(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#validateAudioFormat, [filePath]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getFileSize(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#getFileSize, [filePath]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<DateTime> getDateAdded(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#getDateAdded, [filePath]),
            returnValue: _i3.Future<DateTime>.value(
              _FakeDateTime_0(
                this,
                Invocation.method(#getDateAdded, [filePath]),
              ),
            ),
          )
          as _i3.Future<DateTime>);
}

/// A class which mocks [MetadataDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetadataDataSource extends _i1.Mock
    implements _i5.MetadataDataSource {
  MockMetadataDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> extractMetadata(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#extractMetadata, [filePath]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<String?> extractAndSaveAlbumArt(
    String? filePath,
    _i6.Uint8List? albumArtData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#extractAndSaveAlbumArt, [
              filePath,
              albumArtData,
            ]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i7.AudioFormat getAudioFormat(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#getAudioFormat, [filePath]),
            returnValue: _i7.AudioFormat.flac,
          )
          as _i7.AudioFormat);
}

/// A class which mocks [LocalDatabaseDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDatabaseDataSource extends _i1.Mock
    implements _i8.LocalDatabaseDataSource {
  MockLocalDatabaseDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insertTrack(_i9.AudioTrackModel? track) =>
      (super.noSuchMethod(
            Invocation.method(#insertTrack, [track]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertTracks(List<_i9.AudioTrackModel>? tracks) =>
      (super.noSuchMethod(
            Invocation.method(#insertTracks, [tracks]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i10.Track>> getAllTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTracks, []),
            returnValue: _i3.Future<List<_i10.Track>>.value(<_i10.Track>[]),
          )
          as _i3.Future<List<_i10.Track>>);

  @override
  _i3.Future<_i10.Track?> getTrackById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackById, [id]),
            returnValue: _i3.Future<_i10.Track?>.value(),
          )
          as _i3.Future<_i10.Track?>);

  @override
  _i3.Future<List<_i10.Track>> getTracksByArtist(String? artist) =>
      (super.noSuchMethod(
            Invocation.method(#getTracksByArtist, [artist]),
            returnValue: _i3.Future<List<_i10.Track>>.value(<_i10.Track>[]),
          )
          as _i3.Future<List<_i10.Track>>);

  @override
  _i3.Future<List<_i10.Track>> getTracksByAlbum(String? album) =>
      (super.noSuchMethod(
            Invocation.method(#getTracksByAlbum, [album]),
            returnValue: _i3.Future<List<_i10.Track>>.value(<_i10.Track>[]),
          )
          as _i3.Future<List<_i10.Track>>);

  @override
  _i3.Future<List<String>> getAllArtists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllArtists, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getAllAlbums() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAlbums, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i10.Track>> searchTracks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTracks, [query]),
            returnValue: _i3.Future<List<_i10.Track>>.value(<_i10.Track>[]),
          )
          as _i3.Future<List<_i10.Track>>);

  @override
  _i3.Future<List<_i10.Track>> getTracksByFormat(_i7.AudioFormat? format) =>
      (super.noSuchMethod(
            Invocation.method(#getTracksByFormat, [format]),
            returnValue: _i3.Future<List<_i10.Track>>.value(<_i10.Track>[]),
          )
          as _i3.Future<List<_i10.Track>>);

  @override
  _i3.Future<void> deleteTrack(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrack, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllTracks() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllTracks, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getTrackCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTrackCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> insertPlaylist(
    String? id,
    String? name,
    DateTime? createdAt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertPlaylist, [id, name, createdAt]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i10.Playlist>> getAllPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlaylists, []),
            returnValue: _i3.Future<List<_i10.Playlist>>.value(
              <_i10.Playlist>[],
            ),
          )
          as _i3.Future<List<_i10.Playlist>>);

  @override
  _i3.Future<_i10.Playlist?> getPlaylistById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistById, [id]),
            returnValue: _i3.Future<_i10.Playlist?>.value(),
          )
          as _i3.Future<_i10.Playlist?>);

  @override
  _i3.Future<void> updatePlaylist(
    String? id,
    String? name,
    DateTime? updatedAt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylist, [id, name, updatedAt]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePlaylist(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addTrackToPlaylist(
    String? playlistId,
    String? trackId,
    int? position,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackToPlaylist, [
              playlistId,
              trackId,
              position,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeTrackFromPlaylist(
    String? playlistId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrackFromPlaylist, [playlistId, trackId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getPlaylistTrackIds(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistTrackIds, [playlistId]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> reorderPlaylistTracks(
    String? playlistId,
    List<String>? trackIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderPlaylistTracks, [playlistId, trackIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveSetting(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveSetting, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getSetting(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSetting, [key]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [PermissionDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionDataSource extends _i1.Mock
    implements _i11.PermissionDataSource {
  MockPermissionDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> requestStoragePermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestStoragePermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> checkStoragePermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkStoragePermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> shouldShowPermissionRationale() =>
      (super.noSuchMethod(
            Invocation.method(#shouldShowPermissionRationale, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
