// Mocks generated by Mockito 5.4.6 from annotations
// in mmine/test/features/music_player/data/repositories/playlist_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mmine/features/music_player/data/datasources/database.dart'
    as _i2;
import 'package:mmine/features/music_player/data/datasources/playlist_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylist_1 extends _i1.SmartFake implements _i2.Playlist {
  _FakePlaylist_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlaylistDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistDataSource extends _i1.Mock
    implements _i3.PlaylistDataSource {
  MockPlaylistDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeAppDatabase_0(this, Invocation.getter(#database)),
          )
          as _i2.AppDatabase);

  @override
  _i4.Future<List<_i2.Playlist>> getAllPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlaylists, []),
            returnValue: _i4.Future<List<_i2.Playlist>>.value(<_i2.Playlist>[]),
          )
          as _i4.Future<List<_i2.Playlist>>);

  @override
  _i4.Future<_i2.Playlist?> getPlaylistById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistById, [id]),
            returnValue: _i4.Future<_i2.Playlist?>.value(),
          )
          as _i4.Future<_i2.Playlist?>);

  @override
  _i4.Future<_i2.Playlist> createPlaylist(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#createPlaylist, [name]),
            returnValue: _i4.Future<_i2.Playlist>.value(
              _FakePlaylist_1(this, Invocation.method(#createPlaylist, [name])),
            ),
          )
          as _i4.Future<_i2.Playlist>);

  @override
  _i4.Future<void> updatePlaylist(_i2.Playlist? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylist, [playlist]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePlaylist(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getPlaylistTrackIds(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistTrackIds, [playlistId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addTrackToPlaylist(String? playlistId, String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackToPlaylist, [playlistId, trackId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeTrackFromPlaylist(
    String? playlistId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrackFromPlaylist, [playlistId, trackId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reorderPlaylistTracks(
    String? playlistId,
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderPlaylistTracks, [
              playlistId,
              oldIndex,
              newIndex,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
