// Mocks generated by Mockito 5.4.6 from annotations
// in mmine/test/features/music_player/domain/usecases/playlist/delete_playlist_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mmine/core/error/failures.dart' as _i5;
import 'package:mmine/features/music_player/domain/entities/playlist.dart'
    as _i6;
import 'package:mmine/features/music_player/domain/repositories/playlist_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlaylistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistRepository extends _i1.Mock
    implements _i3.PlaylistRepository {
  MockPlaylistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Playlist>>> getAllPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPlaylists, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Playlist>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Playlist>>(
                    this,
                    Invocation.method(#getAllPlaylists, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Playlist>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Playlist>> getPlaylistById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistById, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Playlist>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Playlist>(
                    this,
                    Invocation.method(#getPlaylistById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Playlist>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Playlist>> createPlaylist(
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPlaylist, [name]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Playlist>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Playlist>(
                    this,
                    Invocation.method(#createPlaylist, [name]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Playlist>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updatePlaylist(
    _i6.Playlist? playlist,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaylist, [playlist]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updatePlaylist, [playlist]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deletePlaylist(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deletePlaylist, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addTrackToPlaylist(
    String? playlistId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTrackToPlaylist, [playlistId, trackId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#addTrackToPlaylist, [playlistId, trackId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeTrackFromPlaylist(
    String? playlistId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrackFromPlaylist, [playlistId, trackId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeTrackFromPlaylist, [
                  playlistId,
                  trackId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> reorderPlaylistTracks(
    String? playlistId,
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderPlaylistTracks, [
              playlistId,
              oldIndex,
              newIndex,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#reorderPlaylistTracks, [
                  playlistId,
                  oldIndex,
                  newIndex,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
